name: Build and Deploy Next.js Project

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js project
        run: yarn build

      - name: Archive static files
        run: tar -czf nextjs-static-files.tar.gz -C out .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-static-files
          path: nextjs-static-files.tar.gz

  deploy-to-vps:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: nextjs-static-files

      - name: Extract artifact
        run: tar -xzf nextjs-static-files.tar.gz

      - name: Transfer artifact to server
        run: scp -P ${{ secrets.VPS_PORT }} nextjs-static-files.tar.gz ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~

      - name: SSH and deploy static files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            mkdir -p ~/samschooler.com/www
            rm -rf ~/samschooler.com/www/*
            tar -xzf nextjs-static-files.tar.gz -C ~/samschooler.com/www
